---
- name: Verify
  hosts:
    - subjects
  tasks:
    - name: Check if HashiCorp Packer package is installed
      check_mode: true
      become: true
      ansible.builtin.package:
        name:
          - packer
        state: present
      register: _packer_package

    - name: Verify HashiCorp Packer package is installed
      ansible.builtin.assert:
        that:
          - _packer_package is not changed
        fail_msg: HashiCorp Packer package is not installed.
        success_msg: HashiCorp Packer package is installed.
