---
- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Configure repository
  ansible.builtin.include_tasks: "repo/{{ ansible_os_family }}.yml"

- name: Install
  ansible.builtin.import_tasks: install.yml
